typography_spectrum: 0.9967257692478597
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8969390999991447
  lightness: 0.865846854634583
  saturation: 0.4271750736515969
  rhythmicContrast: 0.1097039335872978
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1703884149901569
analytics:
  google: null
  facebook: null
  twitter: null
name: thegloriousrevolution
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Glorious Revolution
purpose: []
